version: '3.8'

services:
  ldca_chat:
    container_name: "ldca_chat"
    image: ldca-chat:0.0.1
    ports:
      - "8081:8081"
    depends_on:
      - mongo
      - kafka
    networks:
      - ldca_network

  ldca_chatroom:
    container_name: "ldca_chatroom"
    image: ldca-chatroom:0.0.1
    ports:
      - "8082:8082"
    depends_on:
      - mongo
      - kafka
    networks:
      - ldca_network

  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
      - ./front:/front
    depends_on:
      - ldca_chat
      - ldca_chatroom
    networks:
      - ldca_network

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
#    volumes:
#      - ./mongodb/data:/data/db
    networks:
      - ldca_network

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - ldca_network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
#    volumes:
#      - ./kafka/data:/bitnami/kafka
    networks:
      - ldca_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_NAME=peters_kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - ldca_network

networks:
  ldca_network:
    driver: bridge